# Generated by Django 4.0.3 on 2022-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ophtalmo_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ophtalmo_article_images')),
                ('text', models.TextField(blank=True)),
                ('photo_dedication', models.CharField(blank=True, max_length=128)),
                ('auteur', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
    ]
