# Generated by Django 4.0.3 on 2022-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ophtalmo_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ophtalmo_center_images')),
                ('description', models.TextField(blank=True)),
                ('marque_laser_excimer', models.CharField(max_length=128)),
                ('date_maintenance_laser_excimer', models.DateField()),
                ('marque_laser_femtosecond', models.CharField(max_length=128)),
                ('date_maintenance_laser_femtosecond', models.DateField()),
                ('lien_site_internet', models.URLField(max_length=128)),
            ],
        ),
    ]
